### ISSUE TITLE
9/1 Check-mate 구현 목표

### ISSUE THREAD

**Issue by wplong11** [mash-up-kr/Checkmate-ios#1]
# Check-mate
## 핵심 기능
- 근태 기록을 바탕으로 받을 돈을 자동으로 계산한다.

## 핵심 유저 스토리
- [ ] #2 유저는 알바 근무지를 관리한다.
	- 현재 알바 근무지를 등록/조회/수정할 수 있다.
- [ ] #3 유저는 알바 근무지와 관련된 근태 정보를 관리한다.
	- 출근/퇴근/휴식 시간 정보를 추가/조회/수정/삭제할 수 있다.
- [ ] #4 유저는 받을 돈을 확인한다. 받을 돈은 자동으로 계산된다.

## 부가 기능
- [ ] #5  GPS 를 사용한 **Reminder** 푸시 알림
	- 알바 장소에 **도착**하고 일정 시간이 흘렀음에도 근태 정보를 기록하지 않은 경우 **Reminder** 푸시 알림을 노출한다.
	- 알바 장소를 **이탈**하고 일정 시간이 흘렀음에도 근태 정보를 기록하지 않은 경우 **Reminder** 푸시 알림을 노출한다.

## 9/1, 구현 목표
- 근태 기록과 받을 돈 계산 기능은 단일 근무지에 대해서만 제공한다. 여러 근무지를 등록하는 기능은 이번 작업 계획에서 제외한다.
- 시급 계산 기능은 알바몬 수준으로 구현한다.
	- http://m.alba.co.kr/story/Calculator.asp

### 구현할 기능
- [ ] #6 현재 근무지 정보 관리(등록/조회/수정/삭제)
	- 근무지 정보: 시급 / 업체명 / 세금 적용 여부 / 수습 적용 여부 / 지리적 위치(GPS)
	- 근부지 정보를 삭제하면 관련된 근태 기록을 모두 삭제한다.
	- 근무지 정보 등록은 두가지 경우가 있다.
		- 근무지 정보가 없는 경우
		- 근무지 정보가 이미 있는 경우
			- 이 경우는 유저가 새 일자리를 구할 때 발생한다. 단순히 근무지 정보만 변경하는 기능과 다르다. 근무지 정보를 변경하면 근태 기록이 유지되지만, 근무지를 새로 등록하면 현재 근무지와 관련된 근태 기록은 하나도 없는 상태가 된다.

- [ ] #7 과거 근무지 정보 관리(조회/수정/삭제)

- [ ] #8 근태 정보 관리(추가/조회/수정/삭제)
	- 근태 정보: 출근 시간 / 휴식 시작 시간 / 휴식 종료 시간 / 퇴근 시간

- [ ] #5 GPS 를 사용한 **Reminder** 푸시 알림

### 작업 계획
유저에게 보여줄 정보와 그것의 화면 배치에 관한 정보를 포함한 와이어프레임과 화면 흐름을 결정한 이후에 개발  계획을 세운다. 대략적인 계획은 다음과 같다.
- ~ 2018.07.18
	- 디자이너 / 개발자: 와이어 프레임과 화면 흐름을 논의하고 검토한다.
	- 디자이너: 와이어 프레임과 화면 흐름을 스케치 파일로 정리해서 팀에 공유한다.
- ~ 2018.07.23
	- 디자이너 / 개발자: 와이어 프레임과 화면 흐름을 확정한다.
	- 디자이너: 와이어 프레임과 화면 흐름을 **확정**하고 스케치 파일로 정리해서 팀에 공유한다.
- ~ 2018.07.30
	- 디자이너: 시각 디자인 작업을 한다.
	- 모바일앱: 시각 디자인이 없는 상태로 앱을 구현한다.
	- 서버: 모바일 개발자와 논의해서 API 를 확정한다.
- ~ 2018.08.06
	- 디자이너: 시각 디자인 작업을 한다.
	- 모바일앱: 시각 디자인이 없는 상태로 앱을 구현한다.
	- 서버: API 를 구현한다.
- ~ 2018.08.13
	- 디자이너: 시각 디자인 작업을 한다.
	- 모바일앱: 시각 디자인이 없는 상태로 앱을 구현한다.
	- 서버: API 를 구현한다.
- ~ 2018.08.20
	- 디자이너: 시각 디자인 작업을 한다.
	- 모바일앱: 시각 디자인을 적용한다.
	- 서버: API 를 구현한다.
- ~ 2018.08.27
	- 디자이너: 시각 디자인을 작업한다.
	- 모바일앱: 시각 디자인을 적용한다.
	- 서버: API 를 구현한다.
## Q&A
- Q. GPS 를 사용해서 근태 정보를 자동으로 기록하는 최초 기획과 다르게, 수동으로 기록하는 이유가 뭐에요?
	- A.  근무지에 도착한 시간과 업무를 개시한 시간이 일치하지 않는 문제가 있습니다. 게다가 두 시간 사이의 공백 시간이 긴 경우도 있습니다. 유저에게 주는 편의성보다 정확성이 더 중요하다고 생각해서 근태 기록을 수동으로 입력하도록 했습니다.  대신 유저가 근태 정보를 입력하는 것을 까먹는 문제를 방지하기 위한 기능에 GPS 기술을 적용했습니다.
- Q. 근무지를 여러개 등록하는 기능은 불필요한가요?
	- A. 필요합니다. 하지만 여러 근무지에서 일 하는 유저가 실제로 얼마나 될지 모르기 때문에 해당 기능의 효용 가치를 예측하기 어렵습니다. 또한 핵심 기능이 아니기 때문에 작업 우선 순위가 낮다고 판단해서 이번 계획에서 제외하게 됐습니다.
